spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github.client.id}
            client-secret: ${github.client.secret}
            scope: read:user, user:email
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            provider: github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
